### ISSUE TITLE
How are the values of L1, C3 and C4 for antenna decided?

### ISSUE THREAD

**Issue by dataplayer12** [mike-rankin/ESP32_Pico#1]
Hi,

Thank you for open sourcing this project. I am looking to design my own board and I'm stuck on the values of antenna caps and inductor. I understand that the impedances of the PCB and the ESP chip need to be matched. In the datasheet, these values are marked as 'TBD'. 

My question is how did you come up with the values of C3 (47 pF), C4 (2.7 pF) and L1 (1.8 nH)? Did you experiment with different values? Do you expect these values to work on a different board? Are there any rules of thumb about deciding these values? As you can see, my knowledge on RF is minimal, so please share any thoughts that you think a beginner should know. Thank you very much!

**Comment by mike-rankin** [comment]
Those value are most likely incorrect. The datasheet for the antenna should be followed on page 8:
http://www.proant.se/files/user/Documents/Datasheets%20and%20appnotes/Upload%202018-06-08/Application%20note%20-%20OnBoard%20SMD%202400%20MHz%20rev%203.2.pdf

I followed the schematic from Espressif when the pico first came out and made the error. I see Espressif has since made the correction to page 14:
https://datasheet.octopart.com/ESP32-PICO-D4-Espressif-Systems-datasheet-109841465.pdf

**Comment by dataplayer12** [comment]
Thank you for the clarification. By the way, the ESP datasheet has two schematics, 'Schematics' and 'Peripheral Schematics'. How do you decide which one to follow?

**Comment by mike-rankin** [comment]
I'm not sure why you would add a crystal and flash to the pico if it already has these parts inside.

**Comment by dataplayer12** [comment]
What I think you are saying is that I should just follow the 'Schematics' part of the datasheet. You are saying this in a cryptic way, as if it is beneath your dignity to give a straight reply. Anyways, thank you very much. I appreciate you taking the time to address my questions.

**Comment by mike-rankin** [comment]
Sorry, I don't mean to be cryptic. Over the past few months I've made a few designs with mistakes all along the way. The latest Color Coincell schematic is error free as far as I know. If you use this one as a guide you should be good: https://github.com/mike-rankin/ESP32_CoinCell_Color_TFT/tree/master/PCB

**Comment by dataplayer12** [comment]
Sorry if I came across as rude. Thank you for the link. This is a very cool project. In the BOM, you have left out the values of C1 and C2 as requiring tuning, which brings me back to my earlier questions. It seems like one would have to manually try a few options, starting with the values given in data sheet of the antenna.

**Comment by mike-rankin** [comment]
I used to work with an antenna expert who had the hardware and software to tune antennas properly. I added the two pads in case it is possible to have it properly tuned in the future. Right now it works just fine.

**Comment by nevercast** [comment]
Hello again @dataplayer12, seems we have an interest in similar boards. See my comment here regarding tuning https://github.com/tinypico/tinypico-hardware/issues/3 

But as for the ESP32 PICO Datasheet, the "Module Schematics" shows you the internals of the ESP32 PICO, it has many passive and active components inside the silicon. 

When designing your schematic you want to use "Module Peripheral Schematics". Keeping in mind that "Module Schematics" will affect your "Module Peripheral Schematics" design.

Module Schematics => Inside the ESP32 PICO Chip
Module Peripheral Schematics => Outside the ESP32 PICO (Designed by the integrator, you)

**Comment by dataplayer12** [comment]
@nevercast Thanks a lot! I did not know that module schematics refers to circuits already in the Pico chip. Your explanation has saved me many more hours of painful confusion on what to do. I really appreciate it.

**Comment by nevercast** [comment]
One more note. You'll notice there are two antenna matching networks. One inside the PICO and one outside. The one that is outside has TBD and no values. The one inside the PICO has values. 

Ignore the one inside the PICO, that is just to tune the difference between the chip inside the silicon and the pad on the outside. These values do not matter to you.

You will need to determine the TBD components yourself, for the mean time, that would be
C27: Not fitted
C28: Not fitted
L5: 0 ohm resistor.

You can place better componetns once you tune the system, if you choose to do that.

**Comment by dataplayer12** [comment]
@nevercast Wow. I have learnt more in the last 30 minutes than in the last 3 days. Thanks for explaining things in a simple manner. I have ordered a PCB to be fabbed. I am looking forward to trying out your suggestions.

**Comment by nevercast** [comment]
For what it is worth, I have one of these and it does the trick. But maybe learn more about RF before spending the money. https://www.aliexpress.com/item/32961910083.html?spm=a2g0s.9042311.0.0.27424c4dzvQXYo

**Comment by dataplayer12** [comment]
Thanks. I have an Analog Discovery 2 which has a basic VNA. Once I get the boards, I will use that to measure the performance. Hopefully it will do the job.

**Comment by mike-rankin** [comment]
Thanks @nevercast ! I had my antenna parts all wrong. On my CoinCell board I will measure the RSSI with the inductor in place, swap it out for a 0R resistor and test again.

**Comment by nevercast** [comment]
If you have an oscilliscope you might be able to attach that to the antenna signal if you don't have an SWR Meter or VNA. But I have never tried this and I'm not endorsing it, it might be a point of research is all :)
